name: yurfly
markdown: redcarpet
pygments: true
permalink: /:month-:day-:year/:title.html
paginate: 3
author: yurfly
something: stay hungry, stay foolish
email: yurfly(at)gmail.com
github: http://github.com
weibo: http://weibo.com
weixin: http://weixin.qq.com
